### ISSUE TITLE
[warp] implement area enter / leave triggers

### ISSUE THREAD

**Issue by itsjavi** [route1rodent/newbark#16]
- implement triggers for area leave / enter
- useful for displaying route/town titles

**Comment by route1rodent** [comment]
done, with events and the new TriggerListener2D script:


<img width="591" alt="Screenshot 2019-10-11 at 03 27 34" src="https://user-images.githubusercontent.com/18262122/66617873-2dc6a580-ebd7-11e9-9a47-6b0db0afa7a9.png">
