### ISSUE TITLE
[map] add Cherrygrove city

### ISSUE THREAD

**Issue by itsjavi** [route1rodent/newbark#18]
Add Cherrygrove City, with all houses including the Shop and Poke Center.

**Comment by route1rodent** [comment]
done

<img width="1027" alt="Screenshot 2019-10-11 at 03 29 33" src="https://user-images.githubusercontent.com/18262122/66617941-6fefe700-ebd7-11e9-9e58-f5e5cba8e707.png">

 (house interiors, dialogs, etc will come in next versions)
