### ISSUE TITLE
[movement] implement MoveTo/MoveTowards

### ISSUE THREAD

**Issue by itsjavi** [route1rodent/newbark#20]
implement `MoveTo(x,y,speed)` and `MoveTowards` (may need path finder logic) for grid-based movement

useful for NPCs to move in front of the player

this could be part of the move director #21

**Comment by route1rodent** [comment]
done in MovementController2 (name will change without the "2"), but NPC movement may require a little refactoring in order to make it work without the input (NPCs do not need input)
